{
 "title": "SMARTctl Exporter Dashboard",
 "description": "Extended smartctl-exporter Dashboard",
 "tags": [
  "prometheus",
  "node_exporter",
  "smartmon"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(smartctl_version,instance)"
    }
   },
   {
    "name": "disk",
    "query": {
     "query": "label_values(smartctl_device,device)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(smartctl_device,interface)"
    }
   },
   {
    "name": "device_model",
    "query": {
     "query": "label_values(smartctl_device,model_name)"
    }
   },
   {
    "name": "serial_number",
    "query": {
     "query": "label_values(smartctl_device,serial_number)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(smartctl_device_temperature{instance=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}) by (instance,device,model_name)",
     "legendFormat": "{{instance}} {{device}} {{model_name}}"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device{instance=~\"$node\", device=~\"$disk\", interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartctl_device) by (interface)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Media Errors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "smartctl_device_media_errors{instance=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"} > 0",
     "legendFormat": "{{instance}} {{device}} {{model_name}}"
    }
   ]
  },
  {
   "title": "Unhealthy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((smartctl_device_smart_status{instance=~\"$node\",device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device) == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Critical Warnings",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartctl_device_critical_warning{instance=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"} > 0",
     "legendFormat": "Critical Warnings {{device}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(smartctl_device) by (instance))",
     "legendFormat": "nodes"
    }
   ]
  },
  {
   "title": "Disk Lifetime",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max(smartctl_device_power_on_seconds{instance=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}) by (instance, device, model_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(smartctl_device_power_cycle_count{instance=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}) by (instance, device, model_name)",
     "legendFormat": "Power Cycles"
    }
   ]
  },
  {
   "title": "Total Data Written on SSDs",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 8 },
   "targets": [
    {
     "expr": "max(smartctl_device_bytes_written{instance=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}) by (device, instance, model_name, serial_number)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max((smartctl_device_attribute{instance=~\"$node\", device=~\"$disk\", attribute_name=\"Total_LBAs_Written\", attribute_value_type=\"raw\"} * on (instance,device) smartctl_device_block_size{instance=~\"$node\", device=~\"$disk\",blocks_type=\"physical\"}) * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"$type\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"}) by (device, instance, model_name, serial_number)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wear Level on SATA Devices",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(100 - smartctl_device_attribute{instance=~\"$node\", device=~\"$disk\", attribute_name=\"Wear_Leveling_Count\",attribute_value_type=\"value\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"sat\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  },
  {
   "title": "Wear Level on NVMe Devices",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(smartctl_device_percentage_used{instance=~\"$node\", device=~\"$disk\"} * on(instance, device) group_left(interface,serial_number,model_family,model_name) smartctl_device{interface=~\"nvme\",serial_number=~\"$serial_number\",model_name=~\"$device_model\"})\n",
     "legendFormat": "{{instance}}:{{device}}"
    }
   ]
  }
 ]
}