"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[indicator]
padding = { open = "█", close = "█" }

[status]
sep_left = { open = " ", close = " " }
sep_right = { open = " ", close = " " }

[tabs]
active = { fg = "black", bg = "blue", bold = true }
inactive = { fg = "darkgray", bg = "black" }
sep_inner = { open = " ", close = " " }
sep_outer = { open = " ", close = " " }

progress_normal = { fg = "green", bg = "black" }
progress_error = { fg = "yellow", bg = "red" }

[mode]
normal_main = { fg = "black", bg = "blue", bold = true }
normal_alt = { fg = "blue", bg = "black" }
select_main = { fg = "black", bg = "magenta", bold = true }
select_alt = { fg = "magenta", bg = "black" }
unset_main = { fg = "black", bg = "cyan", bold = true }
unset_alt = { fg = "cyan", bg = "black" }

[filetype]
rules = [
  { url = "*", is = "orphan", fg = "cyan", crossed = true },
  { url = "*", is = "exec", fg = "green" },
  { url = "*", is = "link", fg = "cyan" },
  { url = "*/", is = "link", fg = "cyan" },

  # Dummy files
  { url = "*", is = "dummy", bg = "red" },
  { url = "*/", is = "dummy", bg = "red" },

  # Fallback
  { url = "*", fg = "white" },
  { url = "*/", fg = "blue" },
]

[icon]
dirs = []
prepend_conds = [
  { if = "dir", text = "", fg = "blue" },
  { if = "!dir", text = "", fg = "white" },
]
