"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
show_hidden = true
show_symlink = false
mouse_events = []

[preview]
cache_dir = "${HOME}/.cache/yazi/previews"

[plugin]
prepend_fetchers = [
  { id = "git", url = "*", run = "git" },  # for plugin: git
  { id = "git", url = "*/", run = "git" }, # for plugin: git
]

prepend_preloaders = [
  { mime = "{audio,video,image}/*", run = "mediainfo" }, # for plugin: mediainfo
]

prepend_previewers = [
  { mime = "{audio,video,image}/*", run = "mediainfo" }, # for plugin: mediainfo
  { mime = "audio/*", run = "exifaudio" },               # for plugin: exifaudio
]
