# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  systemd.tmpfiles.rules = [
    "d /snapraid/disk1/data 0775 root root -"
    "d /snapraid/disk2/data 0775 root root -"
  ];

  fileSystems = {
    "/snapraid/mergerfs" = {
      device = "/snapraid/disk1/data:/snapraid/disk2/data";
      fsType = "mergerfs";
      options = [
        "cache.files=off"
        "category.create=pfrd"
        "func.getattr=newest"
        "dropcacheonclose=false"
      ];
    };
  };

  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-partuuid/${uuidEFI}";
  #   fsType = "vfat";
  #   options = [
  #     "fmask=0022"
  #     "dmask=0022"
  #   ];
  # };
  #
  # fileSystems."/" = {
  #   device = "/dev/disk0-pool/root";
  #   fsType = "btrfs";
  #   options = [ "subvol=root" ];
  # };
  #
  # fileSystems."/home" = {
  #   device = "/dev/disk0-pool/root";
  #   fsType = "btrfs";
  #   options = [ "subvol=home" ];
  # };
  #
  # fileSystems."/nix" = {
  #   device = "/dev/disk0-pool/root";
  #   fsType = "btrfs";
  #   options = [ "subvol=nix" ];
  # };
  #
  # fileSystems."/snapraid/parity" = {
  #   device = "/dev/disk0-pool/snapraidParity";
  #   fsType = "btrfs";
  #   options = [ "subvol=parity" ];
  # };
  #
  # fileSystems."/data" = {
  #   device = "/dev/disk0-pool/data";
  #   fsType = "btrfs";
  #   options = [ "subvol=data" ];
  # };
  #
  # swapDevices = [
  #   { device = "/dev/disk0-pool/swap"; }
  # ];
  #
  # fileSystems."/snapraid/disk1" = {
  #   device = "/dev/disk1-pool/root";
  #   fsType = "btrfs";
  #   options = [ "subvol=sub1" ];
  # };
  #
  # fileSystems."/snapraid/disk2" = {
  #   device = "/dev/disk2-pool/root";
  #   fsType = "btrfs";
  #   options = [ "subvol=sub1" ];
  # };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
