# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

let
  config-values = import ./config_values.nix;
in
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a15571ba-39fb-4ac0-9302-01a4b5cc945c";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/a15571ba-39fb-4ac0-9302-01a4b5cc945c";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/a15571ba-39fb-4ac0-9302-01a4b5cc945c";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
    options = [ "umask=0077" ];
  };

  systemd.tmpfiles.rules = [
    "d /home/${config-values.username}/data 0755 ${config-values.username} users -"
    "d /home/${config-values.username}/data/samba-share 0775 samba-user samba-group -"
  ];

  fileSystems."/home/${config-values.username}/data" = {
    device = "/dev/disk/by-uuid/c9e1a728-7580-4c7d-8d97-74768f80825e";
    fsType = "btrfs";
    options = [
      "subvol=data"
      "x-systemd.allow-user"
      "user"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/f6114f2b-c736-45a8-9153-dbeb06f6191f"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
