# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/dc52e175-60d8-4811-8798-7614810fd123";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4D46-3725";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/2a07411b-092d-467d-beb3-900cd18bb339";
    fsType = "btrfs";
    options = [ "subvol=data" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/dc52e175-60d8-4811-8798-7614810fd123";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/dc52e175-60d8-4811-8798-7614810fd123";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/snapraid/disk1" = {
    device = "/dev/disk/by-uuid/89f7d4c4-80cc-482d-8b51-3305701ee87e";
    fsType = "btrfs";
    options = [ "subvol=sub1" ];
  };

  fileSystems."/snapraid/disk2" = {
    device = "/dev/disk/by-uuid/ad88c745-5fa0-459d-ae1d-2cae0e2d634a";
    fsType = "btrfs";
    options = [ "subvol=sub1" ];
  };

  fileSystems."/snapraid/parity" = {
    device = "/dev/disk/by-uuid/85042328-41b8-47f1-9f7b-fa3d8eb68991";
    fsType = "btrfs";
    options = [ "subvol=parity" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/6f84f967-d26d-4faa-b7b9-531ee0ed057e"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
